### ISSUE TITLE
Can't understand more obscure youtube.com URLs, like say from a playlist

### ISSUE THREAD

**Issue by KaiMiddleton** [NiklasRosenstein/discord-gmusic-bot#1]
I would like to encourage a fairly non-strict, but safe Regex Solution to filter youtube URLs, find the videoid and return the standard youtu.be short link with the following formatting `https://youtu.be/<videoid>`

The following regex expression will be used to match:
`^https?://[^/]*youtube\.[^/]+/.*[?&]v=([^?&/]+).*$`
You can see a bunch of tests here: https://regex101.com/r/nabnul/1/tests
it is fairly non strict, and will even match obscure stuff that youtube wouldn't allow, but it will only match URLs whos SLD(2nd level domain) is `youtube`, so it should be safe and fine.

It won't match already correctly formatted youtu.be links, and those are already fine.
But if you did want to validate those, the regex would be as follows:
`^https?://youtu\.be/[^?&/]+.*$`

While youtubes character class for video ids, seems to be `[0-9a-ZA-Z_-]`, I couldn't find conformation that they promise it will stay this way, on the other hand, I have never seen a videoid that doesen't comply with this, so if you want a more stricter variant of `[^?&/]+` for matching videoids you could use `[0-9a-ZA-Z_-]+`

In **src/gmusicbot.py** at starting **line 223**, there is the following code
```python
  url = query.strip().lstrip('<').rstrip('>')
  info = urllib.parse.urlparse(url)
  if info.scheme and info.netloc and info.path:
    if 'youtu' in info.netloc:
      player = await self.players.get_player_for_server(message.server, message.author.voice.voice_channel)
      song = await player.queue_song(Player.YoutubeSong, url, user, message.channel, message.timestamp)
    else:
      await self.client.send_message(message.channel, 'That doesn\'t look like a Youtube URL.')
      return
  else:
```

I would add then line:
```python
url = re.sub(r'^https?://[^/]*youtube\.[^/]+/.*[?&]v=([^?&/]+).*$', 'https://youtu.be/\\2', url, flags=re.I)
```
And also make the main check stricter and change:
`if 'youtu' in info.netloc:` into `if 'youtu.be' in info.netloc:`

The block of code I mention earlier, would now look like this:
```python
  url = query.strip().lstrip('<').rstrip('>')
  url = re.sub(r'^https?://[^/]*youtube\.[^/]+/.*[?&]v=([^?&/]+).*$', 'https://youtu.be/\\2', url, flags=re.I)
  info = urllib.parse.urlparse(url)
  if info.scheme and info.netloc and info.path:
    if 'youtu.be' in info.netloc:
      player = await self.players.get_player_for_server(message.server, message.author.voice.voice_channel)
      song = await player.queue_song(Player.YoutubeSong, url, user, message.channel, message.timestamp)
    else:
      await self.client.send_message(message.channel, 'That doesn\'t look like a Youtube URL.')
      return
  else:
```

I am almost certain this was not worth it, and it would been easier just to talk about it, but oh well >.<

**Comment by NiklasRosenstein** [comment]
Thanks for reporting this issue and suggesting a possible solution. I've implemented your suggestions in 720780c although not using a regular expression but instead parsing the URL properly and constructing the `youtu.be/...` URL.
