### ISSUE TITLE
Bot does nothing even though online?

### ISSUE THREAD

**Issue by Sobeked** [NiklasRosenstein/discord-gmusic-bot#3]
Trying the bot on my test server doesn't seem to be working. The bot is running in a docker vm and its online in Discord, but even if I mention it like "@discord-gmusic-bot" or create the separate voice or text channel named "discord-gmusic-bot", it just wont reply or join the voice channel. I even tried "help". I even see the bot_1 messages in cmd with no errors. I am new to this type of stuff , but what am I doing wrong?

**Comment by NiklasRosenstein** [comment]
Closed due to lack of response. Feel free to reopen.
